server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/quanlytrungtam
    username: root
    password: 123456
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  mail:
    host: smtp.gmail.com
    port: 587
    username: sharenamngo@gmail.com
    password: 10a11thanga
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
api:
  prefix: api/v1
jwt:
  expiration: 2592000 #30 days = 30 * 24 * 60 * 60
  secretKey: 54455357342478364763268483726487236482638746283764832



